### PR TITLE
fix meta import of importDirectory() for fileloader.ts

### PR DESCRIPTION
**Pull request by damfle**
Broken for at least Fedora. Should work everywhere now :)

### CODE REVIEW

**Review by ayntee — APPROVED** [review]
LGTM (tested on Linux Mint) ― @Skillz4Killz, thoughts?

**Comment by itohatweb** [comment]
No this does not work on Windows. I only tested the function on Windows, Arch and Debian next time I'll test fedora too.

**Comment by itohatweb** [comment]
Please remove this Dockerfile Commit.

**Comment by damfle** [comment]
Yup sorry. I should have made a branch for the change. Fixing this

**Comment by damfle** [comment]
Too specifics on running the bot from /usr/src on Linux

**Pull request closed without merging**
